### PR TITLE
Add getCapability method to ConnectableDevice

### PR DESCRIPTION
**Pull request by frolov-alexey**
These changes add a new getCapability method for solving that issue https://github.com/ConnectSDK/Connect-SDK-Android/issues/201

### CODE REVIEW

**Comment by frolov-alexey** [comment]
@iheart2code Could you please explain how it should be? I didn't get about gradle plugin here.

**Comment by khk624** [comment]
Maybe we can rename the getApiController to getCapability, in that case he can add new capabilities without modifying the method.

**Comment by iheart2code** [comment]
Sounds like a great idea, @khk624

**Comment by khk624** [comment]
I'm going to close this.

Instead, this is going to be merged in these two branches.
https://github.com/ConnectSDK/Connect-SDK-Android-Core/pull/27
https://github.com/ConnectSDK/Connect-SDK-Android-Google-Cast/pull/7

**Pull request merged**
